from enum import Enum


class TeamStadisticsTypes(Enum):
    LOCAL_PLAYED_GAMES = "Local Played Games"
    AWAY_PLAYED_GAMES = "Away Played Games"
    TOTAL_PLAYED_GAMES = "Total Played Games"
    LOCAL_WINS = "Local Wins"
    AWAY_WINS = "Away Wins"
    TOTAL_WINS = "Total Wins"
    LOCAL_DRAWS = "Local Draws"
    AWAY_DRAWS = "Away Draws"
    TOTAL_DRAWS = "Total Draws"
    LOCAL_LOSES = "Local Loses"
    AWAY_LOSES = "Away Loses"
    TOTAL_LOSES = "Total Loses"
    HOME = "Home"
    AWAY = "Away"
    TOTAL = "Total"

    BEST_TIME_GOAL_SCORED = "Best time to scored a goal"
    BEST_TIME_GOAL_AGAINST = "Best time to against a goal"
    LOCAL_SCORED_GOAL = "Local Scored goal"
    LOCAL_AVERAGE_SCORED_GOAL = "Local average scored goal"
    TOTAL_LOCAL_SCORED_GOAL = "Total local scored goal"
    TOTAL_LOCAL_AVERAGE_SCORED_GOAL = "Total local average scored goal"
    AWAY_SCORED_GOAL = "Away Scored goal"
    AWAY_AVERAGE_SCORED_GOAL = "Away average scored goal"
    TOTAL_AWAY_SCORED_GOAL = "Total away scored goal"

    TO_SCORED = "Goals scored"
    AGAINST_ME = "Goals against"
    GOALS = "Goals"

    CARDS = "Cards"
    OVER = "Over"
    UNDER = "Under"

    WINS = "Wins"
    DRAWS = "Draws"
    LOSES = "Loses"

    BIGGEST_HOME_WIN = "Biggest local win"
    BIGGEST_AWAY_WIN = "Biggest away win"
    BIGGEST_HOME_LOSS = "Biggest home loss"
    BIGGEST_AWAY_LOSS = "Biggest away loss"
    BIGGEST_HOME_SCORED_GOALS = "Biggest home scored goals"
    BIGGEST_AWAY_SCORED_GOALS = "Biggest away scored goals"
    BIGGEST_HOME_GOALS_AGAINST = "Biggest home goals against"
    BIGGEST_AWAY_GOALS_AGAINST = "Biggest away goals against"
    STREAKS_WINS = "Streak wins"
    STREAKS_DRAW = "Streak draw"
    STREAKS_LOSES = "Streak loses"

    CLEAN_HOME_SHEET = "Clean home sheet"
    CLEAN_AWAY_SHEET = "Clean away sheet"
    CLEAN_TOTAL_SHEET = "Total clean sheet"
    FAILED_TO_SCORE_HOME = "Failed to score home"
    FAILED_TO_SCORE_AWAY = "Failed to score away"
    TOTAL_FAILED_SCORE = "Total failed to score"
    PENALTY_SCORED = "Total penalty scored"
    PERCENTAGE_PENALTY_SCORED = "Percentage penalty scored"
    PENALTY_MISSED = "Total penalty missed"
    TOTAL_PENALTY = "Total penalty"
    PERCENTAGE_PENALTY_MISSED = "Percentage penalty missed"
    LINEUPS = "Lineups"
    MOST_COMMON_LINEUP = "Most common lineup"
    LARGEST_NUMBER_COMMON_LINEUP = "Largest number common lineup"
    YELLOW_CARDS = "Yellow cards"
    RED_CARDS = "Red cards"
    MATCHES = "Matches"
    BIGGEST = "Biggest"
